def create_results(legal_form='SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ'):
    return {
        'krs': '123456789',
        'first_entry_date': '2005-06-15',
        'w_likwidacji': False,
        'w_zawieszeniu': False,
        'last_entry_no': 18,
        'id': 236214,
        'last_state_entry_no': 18,
        'last_state_entry_date': '2019-07-08',
        'remove_validation_date': None,
        'name': 'ALIA JUSTITIA SPÓŁKA Z OGRANICZONĄ ODPOWIEDZIALNOŚCIĄ',
        'current_relations_count': 2,
        'ngo_insert_date': None,
        'historical_relations_count': 2,
        'address': {
            'city': 'Łęczyca',
            'code': '99-100',
            'street': 'Pl. Kościuszki',
            'house_no': '6',
            'country': 'Polska',
            'apr_no': None,
            'post_office': 'Łęczyca'},
        'nip': '5070024451',
        'legal_form': legal_form,
        'data_fetched_at': '2020-04-10 02:22:14',
        'type': 'KrsOrganization',
        'regon': '100053128',
        'business_insert_date': '2005-06-15',
        'last_entry_date': '2019-07-08',
        'w_upadlosci': False,
        'is_removed': False,
        'ceo': {
            'krs_person_id': 366511,
            'first_name': 'Mariusz',
            'last_name': 'Moruzgała',
            'name': 'Mariusz Jakub Moruzgała'},
        'name_short': 'ALIA JUSTITIA',
        'duns': '522748219',
        'is_opp': False}
